// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYc0tY3lef2TWWo6qa2OS7aJWg93OBozc',
    appId: '1:529614761948:android:9d6373b18e59b3d1aa2919',
    messagingSenderId: '529614761948',
    projectId: 'we-chat-1d42c',
    storageBucket: 'we-chat-1d42c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbAO5tb6MCWUYc5aWTilZ1Vcs2JhhrxyY',
    appId: '1:529614761948:ios:752a5dd0269c49d8aa2919',
    messagingSenderId: '529614761948',
    projectId: 'we-chat-1d42c',
    storageBucket: 'we-chat-1d42c.appspot.com',
    androidClientId: '529614761948-bdrt4c5vhjkh7s9l66r9ciastoqieufc.apps.googleusercontent.com',
    iosClientId: '529614761948-9or3ljjavsj264lreccl1rkq2qebh09p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}